### ISSUE TITLE
Allow more granular thresholds?

### ISSUE THREAD

**Issue by zachrip** [pavelkukov/q-floodfill#10]
For example I'd like to completely ignore the alpha channel when comparing pixels.

**Comment by pavelkukov** [comment]
Hi @zachrip ,
Thank you for raising this. 
Yes, I agree. This should be improved.

I was thinking for the same feature. My idea is to allow for a replacement of the comparison function.
e.g
```
const floodFill = new FloodFill(imgData)
floodFill.isSameColor = (a: ColorRGBA, b: ColorRGBA, tolerance = 0,) => boolean
floodFill.fill(....)
```
I will try to implement it as soon as possible. Otherwise, a PR with that is welcome. :)

Cheers,
Pavel

**Comment by pavelkukov** [comment]
Hey @zachrip , I've made changes to allow for custom color comparison. 
Now is possible to provide overrides for dependency functions. You can find more details in the ReadMe.

It looks like this:
```typescript
// Compare colors as difference in contrast
// See: https://www.w3.org/TR/AERT/#color-contrast
function isSameColor(a: ColorRGBA, b: ColorRGBA, tolerance = 0): boolean {
    brightnessA = (299 * a.r + 587 * a.g + 114 * a.b) / 1000
    brightnessB = (299 * b.r + 587 * b.g + 114 * b.b) / 1000
    return Math.abs(brightnessA - brightnessB) <= tolerance
}
// Construct flood fill instance
const floodFill = new FloodFill(imgData)
// Set custom implementation
floodFill.isSameColor = isSameColor
// Modify image data
floodFill.fill(fillColor, x, y, 0)
```

Cheers,
Pavel

**Comment by zachrip** [comment]
Thanks @pavelkukov - you rock :D after I launch my game I'll send you a link so you can see it in action :)
