### ISSUE TITLE
Can't import in ObservableHQ

### ISSUE THREAD

**Issue by msurguy** [pavelkukov/q-floodfill#2]
Hi! 
Thank you for the library! 

When I try to import this module in ObservableHQ notebook, I'm getting the following message: 

`Package q-floodfill@1.1.1 does not contain an ES module`

The module loader is relying on the following unpkg.com url : `https://unpkg.com/q-floodfill@1.1.1?module` so I'm wondering what the error might mean. Just wanted to let you know about this behavior as I can import other modules like d3 without problems

It appears there's no default module specified in package.json: https://github.com/rollup/rollup/wiki/pkg.module

![Screen Shot 2020-05-06 at 4 01 09 PM](https://user-images.githubusercontent.com/585833/81236801-dd6bc680-8fb2-11ea-8855-607eab73841d.png)

**Comment by pavelkukov** [comment]
Hi @msurguy ,
Thank you for raising this! I will consider adding ESM bundle in future releases.

The module is packed as a UMD bundle via webpack. The unpkg URL is `https://unpkg.com/q-floodfill@1.1.1/dist/index.bundle.js`

You can use `require` to import it into ObservableHQ. 
Something like
```
FloodFill = (await require("q-floodfill@1.1.1")).default
```
I hope this helps as a temporary solution!

**Comment by msurguy** [comment]
Thank you, that works! 
Please see my vector fill implementation using this package : https://observablehq.com/@msurguy/vector-fill

**Comment by pavelkukov** [comment]
Hey, really cool. Great work.
