### ISSUE TITLE
An option to return canvas with only filled pixels 

### ISSUE THREAD

**Issue by msurguy** [pavelkukov/q-floodfill#3]
Hi! I'd like to know if there is an easy option to return a canvas that only has modified pixels instead of the original canvas + modified pixels.

Thank you!

**Comment by pavelkukov** [comment]
Hi @msurguy ,
The class mutates ImageData directly. 
If you need a canvas with a single black and white area, you have to create it. 
I threw a quick example here: https://codepen.io/pavelkukov/pen/abvYwdd?editors=1011

Did I understand your question correctly?

**Comment by msurguy** [comment]
Thank you! Yes, that is exactly what I was looking for. Thanks again!
